package org.example;

import java.io.FileWriter;
import java.io.IO;
import java.io.IOException;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello, GitHub Pages!");

        String htmlContent = "<html>\n" +
                "<head>\n" +
                "<title>Java Project on GitHub Pages</title>\n" +
                "</head>\n" +
                "<body>\n" +
                "<h1>Welcome to my Java project!</h1>\n" +
                "<p>This page was generated by a Java application and deployed to GitHub Pages.</p>\n" +
                "</body>\n" +
                "</html>";

        String filePath = "target/site/index.html";

        try (FileWriter writer = new FileWriter(filePath)) {
            writer.write(htmlContent);
            System.out.println("HTML файл был успешно сгенерирован по пути: " + filePath);
        } catch (IOException e) {
            System.err.println("Ошибка при записи в файл: " + e.getMessage());
        }
    }
}