name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: ['23']

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  
        folder: target 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
